### PR TITLE
Feature/plot title

### PR DESCRIPTION
**Pull request by f-lukas**
I changed the size of the plots and added a title plus formatting options. The diff shows more changes because I reformated the code. Maybe it is easier to look at the commits.

### CODE REVIEW

**Comment by arunge** [comment]
Currently I have an issue with the import of the online example. I cannot test the app, and want to check what is wrong.

**Review by arunge — CHANGES_REQUESTED** [review]
@f-lukas The issue with the import module occurs only when I have installed a version of DataTools from a feature branch. I will check the issue there and fix it before merging,

Regarding your PR, when I first load a NETCDF file, I get following error:
image

This does not happen if I display another plot first.

**Comment by f-lukas** [comment]
@arunge - Thanks for letting me know. Unfortunately, I could not find out why the relative height is a problem. I changed it to a absolute height which works fine.

**Review by arunge — APPROVED** [review]
Perfect! All is working now. :+1:

**Pull request merged**
